#pragma once
// Airline logos (small square pictures, 16 x 16 pixels as generated by default) for the flight
// tracker. The pictures are stored in flash, run-length compressed; the airline
// is found by its 3-letter ICAO code, which is also the first three letters of
// an airline flight's callsign (UAL1234 -> UAL).

#include <stdint.h>

bool logoAvailable(const char *code);        // code: at least 3 characters, e.g. "UAL"
int  logoCount();
int  logoSize();                             // width and height in pixels

// Draw the logo with its top-left corner at (x, y) on the screen (the padding
// setting applies like for any other drawing).
// brightness: 1..100 percent. Returns false if there is no logo for the code.
bool logoDraw(const char *code, int x, int y, uint8_t brightness);
bool logoDrawScaled(const char *code, int x, int y, uint8_t scale, uint8_t brightness);

// If `callsign` looks like an airline flight (3 letters then a digit), copy its
// 3-letter code to out[4] and return true.
bool logoCodeFromCallsign(const char *callsign, char out[4]);
