#!/usr/bin/env python3
"""Put the User Guide inside the firmware, so the Home page can open it.

Usage:
    python3 tools/make_guide.py  [guide.html]  [output.cpp]

* Reads "PixelPop User Guide.html" (from the folder that holds PixelPop.ino unless you name another
  file), compresses it with gzip, and writes src/core/GuideData.cpp.
* The settings site then serves it at  http://<panel address>/guide  and the Home page has a
  "User guide" button for it. Browsers unpack the gzip by themselves.
* Run it again whenever the guide changes, then upload the sketch. The guide is a snapshot: editing
  the .html file does not change what the panel serves until you do that.
* Needs nothing but Python 3.
"""
import gzip, os, sys

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)                              # the folder with PixelPop.ino
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "PixelPop User Guide.html")
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(root, "src", "core", "GuideData.cpp")

with open(src, "rb") as f:
    html = f.read()
if b"<html" not in html[:2000].lower() and b"<!doctype" not in html[:200].lower():
    sys.exit("That does not look like an HTML file: " + src)

gz = gzip.compress(html, 9, mtime=0)                      # mtime=0: the same guide always gives the same bytes
lines = []
for i in range(0, len(gz), 24):
    lines.append("  " + ",".join(str(b) for b in gz[i:i + 24]) + ",")

with open(out, "w") as f:
    f.write("// GENERATED by tools/make_guide.py from the User Guide - do not edit by hand.\n")
    f.write("// %d bytes of HTML, %d bytes compressed.\n" % (len(html), len(gz)))
    f.write('#include "GuideAssets.h"\n\n')
    f.write("const uint8_t GUIDE_HTML_GZ[] PROGMEM = {\n")
    f.write("\n".join(lines))
    f.write("\n};\n")
    f.write("const size_t GUIDE_HTML_GZ_LEN = %d;\n" % len(gz))
print("%s: %d bytes of HTML -> %d bytes in flash (%s)" % (os.path.basename(src), len(html), len(gz), out))
